### ISSUE TITLE
Option to select a «Reverse mode» feed

### ISSUE THREAD

**Issue by Aginarikar** [kawarimidoll/bluestream#10]
It would be great to choose to see the exact opposite of the default selection of a handle.
Like getting every reaction -to- a handle's action (i.e. to your posts and replies), and exclude every action that the handle itself has initiated on Bluesky.

The reason for asking is mainly because notifications on the Android app doesn't work, and I think there isn't any Notifications API offered for third party apps either.

**Comment by kawarimidoll** [comment]
Thanks for the suggestion.
Since this project does not store user credentials, we would have to monitor the entire bluesky postings to look for reactions to someone in particular.
This would be too heavy. I don't think this is in the scope of this project.
(But I am missing the push notification feature too!)

**Comment by Aginarikar** [comment]
Thanks. Seems notifications have arrived on the latest Android app now! 😊
