### ISSUE TITLE
Enable Feeds as input 

### ISSUE THREAD

**Issue by christianbaumann** [kawarimidoll/bluestream#19]
Enable a bluesky feed (eg https://bsky.app/profile/the-qa-guy.bsky.social/post/3kcm3tpkdie2n) as input.

**Comment by kawarimidoll** [comment]
Thank you for your proposal. However, I don't think it is possible to support feed in Bluesky. Because:
- feed content changes from user to user, so login is required
- bluestream is RSS, so you can't login

In other words, for the same reason as #10, I don't think it is in the scope of this project.
