### ISSUE TITLE
Possible to create one RSS for all people you follow?

### ISSUE THREAD

**Issue by jessicabatke** [kawarimidoll/bluestream#7]
Thanks so much for making this!  

I am hoping to create one single RSS feed that combines all people I follow on Bluesky (I had something similar for Twitter, where I had one RSS feed for everyone I had put on a particular list. RIP).

Right now, it looks like the only way I can follow others by RSS is to create an individual feed for each of their accounts.  Not impossible, but certainly a lot messier in my RSS reader.

Is there a way I could use this project to create one RSS feed for everyone I'm following?

**Comment by kawarimidoll** [comment]
Thank you for creating issue 🥰 

My answer is : you can't do that in https://bluestream.deno.dev but you can do that in your own environment and your own credentials.
Please fork and update this project to create your timeline feed.

This project uses `getAuthorFeed` to get the posts of a specific user. We can retrieve the posts of followees by changing this to `getTimeline`.
However, this only returns timeline of login user, then password is needed  (this is the limitation of atproto-api 😓  ).
It is difficult to store credentials because this project is RSS feed, so I do not plan to add the feature.
