### ISSUE TITLE
docker image?

### ISSUE THREAD

**Issue by untitaker** [kawarimidoll/bluestream#8]
i want to self-host this but don't want to deal with deno. would you accept a PR that adds Dockerfile and publishes to github container registry on push?

**Comment by kawarimidoll** [comment]
Thanks for the proposal 🥰 
I'm glad to hear your suggestion, but I'm not familiar enough with Docker to maintain it.
Therefore, I do not intend to merge PR.
Please create your own Dockerfile and maintain it yourself.

**Comment by Nitrousoxide** [comment]
@untitaker 
I forked and created a branch with a working containerfile and deployment worklfow.  It won't push to a container reg because I also don't want to handle the whole ci/cd pipeline, but this will let you use docker or podman to deploy the server using podman or docker build locally.

I also created a PR on this repo, but in case the maintainer decides not to merge it you can find it here:
https://github.com/Nitrousoxide/bluestream/tree/docker
